require 'pathname'
require 'json'

module GenericConverter
  extend FrameworkConverter
  
  def self.name
    'generic'
  end
  
  def self.detect(file_path)
    # Generic converter is a fallback, so it always returns true
    # but we should check if it's actually a Ruby file
    return false unless File.exist?(file_path)
    
    content = File.read(file_path, encoding: 'utf-8')
    filename = File.basename(file_path)
    
    # Basic Ruby test file detection
    is_ruby_file = filename.end_with?('.rb')
    has_test_patterns = content.include?('def test_') || 
                       content.include?('it ') ||
                       content.include?('describe ') ||
                       content.include?('assert_')
    
    is_ruby_file && has_test_patterns
  end
  
  def self.generate_wrapper(entry_point_path, detection_result, translation_result, files_hash)
    original_test_abs = File.expand_path(entry_point_path)
    framework = detection_result[:framework_type] || 'unknown'
    
    <<~RUBY
      # Generic Ruby test wrapper generated by testeranto
      # Hash: #{files_hash}
      # Framework: #{framework}
      # This file loads the test file
      
      puts 'Running generic Ruby test: #{original_test_abs}'
      
      # Generic execution for unknown frameworks
      begin
        load '#{original_test_abs}'
        puts 'Test loaded successfully'
      rescue => error
        puts "Failed to run test: \#{error.message}"
        puts error.backtrace
        exit 1
      end
    RUBY
  end
  
  def self.translate_to_testeranto(detection_result)
    framework = detection_result[:framework_type] || 'unknown'
    
    {
      specification: <<~RUBY,
        # Generated specification for #{framework} tests
        specification = ->(Suite, Given, When, Then) do
          [
            Suite.Default("#{framework} Tests", {
              "test": Given.Default(
                ["#{framework} test suite"],
                [
                  When.Default("run test", ->(store) {
                    # Test execution
                    store
                  })
                ],
                [
                  Then.Default("verify assertions", ->(store) {
                    # Assertions
                    store
                  })
                ]
              )
            })
          ]
        end
      RUBY
      
      implementation: <<~RUBY,
        # Generated implementation for #{framework} tests
        implementation = {
          suites: {
            Default: "#{framework} test suite"
          },
          givens: {
            Default: ->(initial_values) { 
              # Test context
              {}
            }
          },
          whens: {
            run_test: ->(test_name) { 
              ->(store) do
                puts "Running test: \#{test_name}"
                store
              end
            }
          },
          thens: {
            verify: ->(expected) { 
              ->(store) do
                # Verify assertions
                store
              end
            }
          }
        }
      RUBY
      
      adapter: <<~RUBY,
        # Generated adapter for #{framework} tests
        adapter = {
          before_all: ->(input, test_resource) do
            puts '#{framework} before_all'
            input
          end,
          before_each: ->(subject, initializer, test_resource, initial_values) do
            puts '#{framework} before_each'
            subject
          end,
          execute: ->(store, action_cb, test_resource) do
            action_cb.call(store)
          end,
          verify: ->(store, check_cb, test_resource) do
            check_cb.call(store)
          end,
          cleanup_each: ->(store, key) do
            puts '#{framework} cleanup_each'
            store
          end,
          cleanup_all: ->(store) do
            puts '#{framework} cleanup_all'
            store
          end,
          assert: ->(x) { !!x }
        }
      RUBY
    }
  end
end
