require 'pathname'
require 'json'

module MinitestConverter
  extend FrameworkConverter
  
  def self.name
    'minitest'
  end
  
  def self.detect(file_path)
    return false unless File.exist?(file_path)
    
    content = File.read(file_path, encoding: 'utf-8')
    filename = File.basename(file_path)
    
    # Check file naming patterns
    is_named_test = filename.include?('_test.rb') || filename.include?('.test.rb')
    
    # Check for Minitest imports
    has_minitest_import = content.include?('require \'minitest/autorun\'') || 
                         content.include?('require "minitest/autorun"') ||
                         content.include?('require \'minitest/test\'') ||
                         content.include?('require "minitest/test"')
    
    # Check for Minitest patterns
    has_minitest_patterns = content.include?('class ') && 
                           (content.include?('Minitest::Test') || 
                            content.include?('MiniTest::Unit::TestCase'))
    
    is_named_test || has_minitest_import || has_minitest_patterns
  end
  
  def self.generate_wrapper(entry_point_path, detection_result, translation_result, files_hash)
    original_test_abs = File.expand_path(entry_point_path)
    
    <<~RUBY
      # Minitest test wrapper generated by testeranto
      # Hash: #{files_hash}
      # Framework: minitest
      # This file loads and executes Minitest tests
      
      require 'minitest/autorun'
      
      puts 'Running Minitest test: #{original_test_abs}'
      
      # Load the original test file
      load '#{original_test_abs}'
      
      # Minitest/autorun automatically runs tests when files are loaded
      # We just need to ensure the test file is loaded
      
      puts 'Minitest test loaded and should run automatically'
      
      # Note: Minitest/autorun will handle test execution and exit with appropriate code
    RUBY
  end
  
  def self.translate_to_testeranto(detection_result)
    {
      specification: <<~RUBY,
        # Generated specification for Minitest tests
        specification = ->(Suite, Given, When, Then) do
          [
            Suite.Default("Minitest Tests", {
              "minitest-test": Given.Default(
                ["Minitest test suite"],
                [
                  When.Default("run minitest test", ->(store) {
                    # Minitest test execution
                    store
                  })
                ],
                [
                  Then.Default("verify minitest assertions", ->(store) {
                    # Minitest assertions
                    store
                  })
                ]
              )
            })
          ]
        end
      RUBY
      
      implementation: <<~RUBY,
        # Generated implementation for Minitest tests
        implementation = {
          suites: {
            Default: "Minitest test suite"
          },
          givens: {
            Default: ->(initial_values) { 
              # Minitest test context
              {}
            }
          },
          whens: {
            run_test: ->(test_name) { 
              ->(store) do
                puts "Running Minitest test: \#{test_name}"
                store
              end
            }
          },
          thens: {
            verify: ->(expected) { 
              ->(store) do
                # Verify Minitest assertions
                store
              end
            }
          }
        }
      RUBY
      
      adapter: <<~RUBY,
        # Generated adapter for Minitest tests
        adapter = {
          before_all: ->(input, test_resource) do
            # Minitest setup at class level
            puts 'Minitest before_all'
            input
          end,
          before_each: ->(subject, initializer, test_resource, initial_values) do
            # Minitest setup method
            puts 'Minitest before_each'
            subject
          end,
          execute: ->(store, action_cb, test_resource) do
            # Execute Minitest test action
            action_cb.call(store)
          end,
          verify: ->(store, check_cb, test_resource) do
            # Verify Minitest assertions
            check_cb.call(store)
          end,
          cleanup_each: ->(store, key) do
            # Minitest teardown method
            puts 'Minitest cleanup_each'
            store
          end,
          cleanup_all: ->(store) do
            # Minitest class-level teardown
            puts 'Minitest cleanup_all'
            store
          end,
          assert: ->(x) { !!x }
        }
      RUBY
    }
  end
end
