require 'pathname'
require 'json'

module RSpecConverter
  extend FrameworkConverter
  
  def self.name
    'rspec'
  end
  
  def self.detect(file_path)
    return false unless File.exist?(file_path)
    
    content = File.read(file_path, encoding: 'utf-8')
    filename = File.basename(file_path)
    
    # Check file naming patterns
    is_named_spec = filename.include?('_spec.rb') || filename.include?('.spec.rb')
    
    # Check for RSpec imports and patterns
    has_rspec_import = content.include?('require \'rspec\'') || 
                      content.include?('require "rspec"') ||
                      content.include?('RSpec.')
    
    # Check for RSpec DSL patterns
    has_rspec_patterns = content.include?('describe ') && 
                        (content.include?('it ') || content.include?('specify '))
    
    is_named_spec || has_rspec_import || has_rspec_patterns
  end
  
  def self.generate_wrapper(entry_point_path, detection_result, translation_result, files_hash)
    original_test_abs = File.expand_path(entry_point_path)
    
    <<~RUBY
      # RSpec test wrapper generated by testeranto
      # Hash: #{files_hash}
      # Framework: rspec
      # This file loads and executes RSpec tests
      
      require 'rspec'
      
      puts 'Running RSpec test: #{original_test_abs}'
      
      # Load the original test file
      load '#{original_test_abs}'
      
      # Configure RSpec to run and capture results
      RSpec.configure do |config|
        config.color = true
        config.tty = true
        config.formatter = :documentation
      end
      
      # Run RSpec and capture the exit status
      exit_code = RSpec::Core::Runner.run([File.expand_path('#{original_test_abs}')])
      
      if exit_code == 0
        puts 'RSpec tests passed'
      else
        puts "RSpec tests failed with exit code: \#{exit_code}"
        exit exit_code
      end
    RUBY
  end
  
  def self.translate_to_testeranto(detection_result)
    structure = detection_result[:test_structure] || {}
    
    {
      specification: <<~RUBY,
        # Generated specification for RSpec tests
        specification = ->(Suite, Given, When, Then) do
          [
            #{structure[:test_suites]&.map do |suite|
              <<~SUITE
                Suite.#{suite[:name] || 'Default'}("#{suite[:name] || 'RSpec Suite'}", {
                  #{suite[:test_cases]&.map do |test_case|
                    <<~TESTCASE
                      "#{test_case[:name] || 'unnamed_test'}": Given.#{suite[:given_name] || 'Default'}(
                        ["RSpec test: #{test_case[:name] || 'unnamed'}"]
                        [
                          #{test_case[:actions]&.map do |action|
                            "When.#{action[:name] || 'run_test'}('#{action[:name] || 'unnamed action'}', ->(store) {
                              # RSpec action: #{action[:name]}
                              store
                            })"
                          end&.join(",\n                          ") || 'When.Default("placeholder", ->(store) { store })'}
                        ],
                        [
                          Then.Default("RSpec assertions pass", ->(store) {
                            # RSpec assertions would be verified here
                            store
                          })
                        ]
                      )
                    TESTCASE
                  end&.join(",\n                  ") || '# No test cases found'}
                })
              SUITE
            end&.join(",\n            ") || 'Suite.Default("RSpec Tests", {})'}
          ]
        end
      RUBY
      
      implementation: <<~RUBY,
        # Generated implementation for RSpec tests
        implementation = {
          suites: {
            Default: "RSpec test suite"
          },
          givens: {
            Default: ->(initial_values) { 
              # RSpec test context
              {}
            }
          },
          whens: {
            run_test: ->(test_name) { 
              ->(store) do
                puts "Running RSpec test: \#{test_name}"
                store
              end
            }
          },
          thens: {
            verify: ->(expected) { 
              ->(store) do
                # Verify RSpec assertions
                store
              end
            }
          }
        }
      RUBY
      
      adapter: <<~RUBY,
        # Generated adapter for RSpec tests
        adapter = {
          before_all: ->(input, test_resource) do
            # RSpec before(:all) hook
            puts 'RSpec before_all'
            input
          end,
          before_each: ->(subject, initializer, test_resource, initial_values) do
            # RSpec before(:each) hook
            puts 'RSpec before_each'
            subject
          end,
          execute: ->(store, action_cb, test_resource) do
            # Execute RSpec test action
            action_cb.call(store)
          end,
          verify: ->(store, check_cb, test_resource) do
            # Verify RSpec assertions
            check_cb.call(store)
          end,
          cleanup_each: ->(store, key) do
            # RSpec after(:each) hook
            puts 'RSpec cleanup_each'
            store
          end,
          cleanup_all: ->(store) do
            # RSpec after(:all) hook
            puts 'RSpec cleanup_all'
            store
          end,
          assert: ->(x) { !!x }
        }
      RUBY
    }
  end
end
