import fs from 'fs/promises';
import path from 'path';
import type { GraphData } from "../../../../../graph";

export const generateViewSliceUtil = async (
  viewKey: string,
  viewConfig: any,
  graphData?: GraphData
): Promise<void> => {
  // console.log(`[Server] Generating slice for ${viewKey}`);

  const slicesDir = path.join(process.cwd(), "testeranto", "slices", "views");

  // Ensure directory exists
  try {
    await fs.access(slicesDir);
  } catch {
    await fs.mkdir(slicesDir, { recursive: true });
  }

  const slicePath = path.join(slicesDir, `${viewKey}.json`);

  // Use the slicer function from viewConfig if available and graphData is provided
  let sliceData: any;
  const slicer = viewConfig.slicer;
  if (typeof slicer === 'function' && graphData) {
    sliceData = slicer(graphData);
  } else {
    // Fallback placeholder (should not happen in production)
    sliceData = {
      viewKey,
      timestamp: new Date().toISOString(),
      message: "Slice would be generated by view slicer",
      viewConfig
    };
  }

  await fs.writeFile(slicePath, JSON.stringify(sliceData, null, 2), 'utf-8');
  // console.log(`[Server] Generated slice for ${viewKey} at ${slicePath}`);
};
