import { generateFeatureTree } from "./generateFeatureTree";
import { getDocumentationFilesFromGlob } from "./getDocumentationFilesFromGlob";

/**
 * Embed configuration in HTML for stakeholder app
 */
export async function embedConfigInHtml(configs: any): Promise<void> {
  const fs = require('fs');
  const path = require('path');
  const { existsSync, mkdirSync } = require('fs');

  try {
    const reportsDir = path.join(process.cwd(), "testeranto", "reports");

    // Always create directory if needed
    if (!existsSync(reportsDir)) {
      mkdirSync(reportsDir, { recursive: true });
    }

    // First, copy the TypeScript file for bundling
    const tsxPath = path.join(reportsDir, "index.tsx");
    // Note: __dirname may not be available in utils context, so we need to find the file differently
    // For now, we'll create a basic TypeScript file
    const baseTsx = `// This file is auto-generated by Testeranto
// It serves as the entry point for the stakeholder React app

import React from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './components/App';

const container = document.getElementById('root');
if (container) {
  const root = createRoot(container);
  root.render(<App />);
} else {
  console.error('Could not find root element');
}`;
    fs.writeFileSync(tsxPath, baseTsx);

    // Get documentation files if glob pattern exists
    let documentationFiles: string[] = [];
    if (configs.documentationGlob) {
      documentationFiles = getDocumentationFilesFromGlob(configs.documentationGlob);
    }

    // Generate the feature tree
    const featureTree = await generateFeatureTree(configs);

    // Create a sanitized version of configs without functions
    const sanitizedConfigs = {
      ...configs,
      // Remove the featureIngestor function since it can't be serialized
      featureIngestor: undefined,
    };

    // Create a basic HTML template
    const baseHtml = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Testeranto Report</title>
    <style>
        body { font-family: sans-serif; margin: 0; padding: 20px; }
        h1 { color: #333; }
        .loading { text-align: center; margin-top: 50px; }
    </style>
</head>
<body>
    <div id="root">
        <div class="loading">
            <h1>Testeranto Report</h1>
            <p>Loading...</p>
        </div>
    </div>
    <script>
        // Embedded configuration data
        window.__TESTERANTO_CONFIG__ = ${JSON.stringify(sanitizedConfigs, null, 2)};
        window.__TESTERANTO_DOCUMENTATION__ = ${JSON.stringify(documentationFiles, null, 2)};
        window.__TESTERANTO_FEATURE_TREE__ = ${JSON.stringify(featureTree, null, 2)};
    </script>
    <script type="module" src="./index.tsx"></script>
</body>
</html>`;

    // Write the HTML file
    const htmlPath = path.join(reportsDir, "index.html");
    fs.writeFileSync(htmlPath, baseHtml);

  } catch (error) {
    console.error(`[utils] Failed to embed config in HTML:`, error);
    // Try to create a basic HTML file as fallback
    try {
      const reportsDir = path.join(process.cwd(), "testeranto", "reports");
      const htmlPath = path.join(reportsDir, "index.html");
      if (!existsSync(reportsDir)) {
        mkdirSync(reportsDir, { recursive: true });
      }
      const fallbackHtml = `<!DOCTYPE html>
<html>
<head>
  <title>Testeranto Report</title>
  <style>body { font-family: sans-serif; padding: 20px; }</style>
</head>
<body>
  <h1>Testeranto Report</h1>
  <p>Error: Could not load configuration. Please check server logs.</p>
  <script>
    console.error('Failed to load Testeranto report:', ${JSON.stringify(error.message)});
  </script>
</body>
</html>`;
      fs.writeFileSync(htmlPath, fallbackHtml);
    } catch (fallbackError) {
      console.error(
        `[utils] Failed to create fallback HTML:`,
        fallbackError,
      );
    }
  }
}