#!/bin/sh
echo "Connecting to container: unknown"
echo "Service: aider-nodetests-src-vscode-providers-AiderProcessTreeDataProvider-test-AiderProcessTreeDataProvider-test-ts"
echo "Label: aider: src/vscode/providers/AiderProcessTreeDataProvider.test/AiderProcessTreeDataProvider.test.ts"
echo ""
echo "This terminal uses 'docker attach' to connect to the container."
echo ""
echo "For interactive processes (like aider):"
echo "  - Type input directly to interact with the process"
echo "  - Use Ctrl+P, Ctrl+Q to detach without stopping the container"
echo "  - Use Ctrl+C to send interrupt signal"
echo ""
echo "For non-interactive processes:"
echo "  - You will see the container's output"
echo "  - Press Ctrl+C to exit"
echo "  - Avoid typing input unless you know the process expects it"
echo ""
echo "Attaching to container..."
exec docker attach unknown
