import type { GraphManager } from "../graph/index";
import { jsonResponse } from "../serverClasses/Server_Http/jsonResponse";
import { stakeholderHttpAPI } from "../../api/stakeholderHttp";
import { updateMarkdownFile } from "./markdown";

/**
 * Stakeholder-specific graph operations
 */

/**
 * Handle graph updates from stakeholder app
 */
export async function handleStakeholderGraphUpdate(
  nodeId: string,
  updatedAttributes: Record<string, any>,
  graphManager: GraphManager,
  broadcast?: (message: any) => void
): Promise<any> {
  if (!graphManager) {
    throw new Error("Graph manager not available");
  }

  const graph = (graphManager as any).graph;
  const existingNode = graph.hasNode(nodeId);

  if (!existingNode) {
    throw new Error(`Node ${nodeId} not found`);
  }

  // Get the current node to access its metadata
  const currentNode = graph.getNodeAttributes(nodeId);

  // Create update operation
  const timestamp = new Date().toISOString();
  const operation = {
    type: 'updateNode' as const,
    data: {
      id: nodeId,
      ...updatedAttributes
    },
    timestamp
  };

  const update = { operations: [operation], timestamp };
  graphManager.applyUpdate(update);

  // Save the updated graph
  graphManager.saveGraph();

  // Update the corresponding markdown file if it exists
  const nodeMetadata = updatedAttributes.metadata || currentNode.metadata;
  const localPath = nodeMetadata?.localPath;

  if (localPath && typeof localPath === 'string') {
    try {
      // Get the updated node to access all attributes including the generated content
      const updatedNode = graph.getNodeAttributes(nodeId);
      const updatedMetadata = updatedNode.metadata || {};
      
      // Check if we have content in the metadata (should have been generated by applyUpdate)
      const content = updatedMetadata.content;
      
      if (content && typeof content === 'string') {
        // Parse the frontmatter from the content
        const frontmatterRegex = /^---\s*\n([\s\S]*?)\n---\s*\n/;
        const match = content.match(frontmatterRegex);
        let frontmatterData: Record<string, any> = {};
        let body = content;
        
        if (match) {
          try {
            const yamlContent = match[1];
            const yaml = require('js-yaml');
            frontmatterData = yaml.load(yamlContent) || {};
            body = content.slice(match[0].length);
          } catch (error) {
            console.error(`[Stakeholder] Error parsing YAML frontmatter from content:`, error);
            // Fall back to using metadata frontmatter
            frontmatterData = updatedMetadata.frontmatter || {};
          }
        } else {
          // No frontmatter found, use metadata
          frontmatterData = updatedMetadata.frontmatter || {};
        }
        
        // Update the markdown file with the content
        await updateMarkdownFile(localPath, frontmatterData, body);
        console.log(`[Stakeholder] Updated markdown file: ${localPath} with content from metadata`);
      } else {
        // No content in metadata, try to generate it
        const graphManagerAny = graphManager as any;
        if (graphManagerAny && typeof graphManagerAny.generateMarkdownContent === 'function') {
          const generatedContent = graphManagerAny.generateMarkdownContent(updatedNode);
          
          if (generatedContent) {
            // Parse frontmatter from generated content
            const frontmatterRegex = /^---\s*\n([\s\S]*?)\n---\s*\n/;
            const match = generatedContent.match(frontmatterRegex);
            let frontmatterData: Record<string, any> = {};
            let body = generatedContent;
            
            if (match) {
              try {
                const yamlContent = match[1];
                const yaml = require('js-yaml');
                frontmatterData = yaml.load(yamlContent) || {};
                body = generatedContent.slice(match[0].length);
              } catch (error) {
                console.error(`[Stakeholder] Error parsing YAML frontmatter from generated content:`, error);
                frontmatterData = updatedMetadata.frontmatter || {};
              }
            } else {
              frontmatterData = updatedMetadata.frontmatter || {};
            }
            
            await updateMarkdownFile(localPath, frontmatterData, body);
            console.log(`[Stakeholder] Updated markdown file: ${localPath} with generated content`);
          } else {
            console.log(`[Stakeholder] No content generated for node ${nodeId}, using fallback`);
            const frontmatterData = updatedMetadata.frontmatter || {};
            await updateMarkdownFile(localPath, frontmatterData);
          }
        } else {
          console.log(`[Stakeholder] No generateMarkdownContent method, using fallback`);
          const frontmatterData = updatedMetadata.frontmatter || {};
          await updateMarkdownFile(localPath, frontmatterData);
        }
      }
    } catch (error) {
      console.error(`[Stakeholder] Failed to update markdown file ${localPath}:`, error);
      // Don't fail the entire request if markdown update fails
    }
  } else {
    console.log(`[Stakeholder] No localPath found for node ${nodeId}, skipping markdown update`);
  }

  // Broadcast update to WebSocket clients
  if (broadcast) {
    const graphData = graphManager.getGraphData();
    broadcast({
      type: 'graphUpdated',
      message: `Graph updated due to node update: ${nodeId}`,
      timestamp: new Date().toISOString(),
      data: {
        unifiedGraph: graphData
      }
    });
  }

  return {
    success: true,
    message: "Node updated successfully",
    timestamp: new Date().toISOString(),
    newHash: Date.now().toString(36) // Simple hash for now
  };
}

/**
 * Get graph data for stakeholder app
 */
export function getStakeholderGraphData(graphManager: GraphManager): any {
  if (!graphManager) {
    return { nodes: [], edges: [] };
  }
  
  return graphManager.getGraphData();
}

/**
 * Process markdown file changes for stakeholder app
 */
export async function processStakeholderMarkdownChange(
  filePath: string,
  graphManager: GraphManager
): Promise<any> {
  console.log(`[Stakeholder] Processing markdown file change: ${filePath}`);

  if (!graphManager) {
    console.log('[Stakeholder] Graph manager not available');
    return null;
  }

  const { handleMarkdownFileChange } = await import('./markdown');
  const result = await handleMarkdownFileChange(filePath, graphManager);
  
  return result;
}
