// Build script to compile ast_transformer.ts to JavaScript
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

console.log('Building AST transformer...');

try {
  // Check if TypeScript is available
  execSync('tsc --version', { stdio: 'inherit' });
  
  // Compile the TypeScript file
  const tsconfig = {
    compilerOptions: {
      target: 'ES2020',
      module: 'commonjs',
      outDir: '.',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true
    },
    files: ['ast_transformer.ts']
  };
  
  fs.writeFileSync('tsconfig.temp.json', JSON.stringify(tsconfig, null, 2));
  
  execSync('tsc --project tsconfig.temp.json', { stdio: 'inherit' });
  
  // Clean up
  fs.unlinkSync('tsconfig.temp.json');
  
  console.log('AST transformer built successfully!');
} catch (error) {
  console.error('Failed to build AST transformer:', error.message);
  
  // Create a simple JavaScript version as fallback
  console.log('Creating simple JavaScript version...');
  
  const simpleJs = `
// Simple AST transformer (fallback when TypeScript compilation fails)
const fs = require('fs');
const path = require('path');

class NodeASTTransformer {
  static importToTesteranto(filePath, framework) {
    const source = fs.readFileSync(filePath, 'utf-8');
    
    return \`// Generated by Testeranto AST Transformer (simple version)
// Source: \${filePath}
// Framework: \${framework}

import { Suite, Given, When, Then } from 'tiposkripto';

const specification = (Suite, Given, When, Then) => [
  Suite("Imported Test Suite", {
    "test1": Given(
      ["Test from \${framework}"],
      [When("action", (store) => store)],
      [Then("assertion", async (store) => store)]
    )
  })
];

export default specification;\`;
  }

  static exportFromTesteranto(filePath, targetFramework) {
    return \`// Exported to \${targetFramework} format
// Source: \${filePath}

import { describe, it, expect } from '\${targetFramework === 'mocha' ? 'mocha' : '@jest/globals'}';

describe('Exported Suite', () => {
  it('should work', () => {
    expect(true).toBe(true);
  });
});\`;
  }

  static detectFramework(filePath) {
    const source = fs.readFileSync(filePath, 'utf-8');
    if (source.includes('jest')) return 'jest';
    if (source.includes('mocha')) return 'mocha';
    if (source.includes('vitest')) return 'vitest';
    if (source.includes('jasmine')) return 'jasmine';
    return 'unknown';
  }

  static createPairing(filePath, framework) {
    return new Map();
  }
}

module.exports = { NodeASTTransformer };
`;
  
  fs.writeFileSync('ast_transformer.js', simpleJs);
  console.log('Simple JavaScript version created.');
}
