import esbuild from "esbuild";
import type { ITestconfigV2 } from "../../../Types";
import {
  processMetafile
} from "../common";
import nodeConfiger from "./esbuild";

const projectConfigPath = process.argv[2];
const nodeConfigPath = process.argv[3];
const testName = process.argv[4];

console.log(`[NODE BUILDER] projectConfigPath:  ${projectConfigPath}`);
console.log(`[NODE BUILDER] nodeConfig:  ${nodeConfigPath}`);
console.log(`[NODE BUILDER] testName:  ${testName}`);

// run esbuild in watch mode using esbuildConfigs. Write to fs the bundle and metafile
async function startBundling(
  nodeConfigs: any,
  projectConfig: ITestconfigV2
) {
  console.log(`[NODE BUILDER] is now bundling:  ${testName}`);
  const n = nodeConfiger(nodeConfigs, testName, projectConfig);

  // Check if we're in dev mode (the server passes mode through environment)
  const isDevMode = process.env.MODE === 'dev' || process.argv.includes('dev');
  
  if (isDevMode) {
    console.log(`[NODE BUILDER] Running in dev mode - starting watch mode`);
    
    // Create a build context for watch mode
    const ctx = await esbuild.context(n);
    
    // Build once initially
    const buildResult = await ctx.rebuild();
    if (buildResult.metafile) {
      await processMetafile(projectConfig, buildResult.metafile, 'node', testName);
    } else {
      console.warn("No metafile generated by esbuild");
    }
    
    // Start watching for changes
    await ctx.watch();
    
    console.log(`[NODE BUILDER] Watch mode active - waiting for file changes...`);
    
    // Keep the process alive
    process.on('SIGINT', async () => {
      console.log("[NODE BUILDER] Shutting down...");
      await ctx.dispose();
      process.exit(0);
    });
    
    // Handle rebuild events
    ctx.on('rebuild', async (result) => {
      console.log(`[NODE BUILDER] Rebuilding due to file changes...`);
      if (result.metafile) {
        await processMetafile(projectConfig, result.metafile, 'node', testName);
        console.log(`[NODE BUILDER] Metafile updated`);
        
        // Trigger test re-run by touching inputFiles.json
        // This will be detected by the Server_Docker's file watcher
        const outputBaseName = n.entryPoints?.[0]?.split('.').slice(0, -1).join('.') || testName;
        const inputFilesPath = `testeranto/bundles/${testName}/${outputBaseName}.mjs-inputFiles.json`;
        try {
          const fs = await import('fs');
          const stats = fs.statSync(inputFilesPath);
          fs.utimesSync(inputFilesPath, stats.atime, new Date());
          console.log(`[NODE BUILDER] Triggered inputFiles.json update`);
        } catch (error) {
          console.error(`[NODE BUILDER] Failed to trigger inputFiles.json update:`, error);
        }
      }
    });

    // Also set up a file watcher for source files to ensure changes are detected
    // This is a backup in case esbuild's watch doesn't catch all changes
    const fs = await import('fs');
    const path = await import('path');
    
    // Watch the src directory for changes
    const srcDir = path.join(process.cwd(), 'src');
    if (fs.existsSync(srcDir)) {
      console.log(`[NODE BUILDER] Setting up additional file watcher for ${srcDir}`);
      
      const watcher = fs.watch(srcDir, { recursive: true }, (eventType, filename) => {
        if (filename && (filename.endsWith('.ts') || filename.endsWith('.js') || filename.endsWith('.tsx') || filename.endsWith('.jsx'))) {
          console.log(`[NODE BUILDER] File change detected: ${eventType} ${filename}`);
          // Trigger a rebuild manually
          ctx.rebuild().then(result => {
            if (result.metafile) {
              processMetafile(projectConfig, result.metafile, 'node', testName).then(() => {
                console.log(`[NODE BUILDER] Manual rebuild completed`);
                
                // Trigger test re-run
                const outputBaseName = n.entryPoints?.[0]?.split('.').slice(0, -1).join('.') || testName;
                const inputFilesPath = `testeranto/bundles/${testName}/${outputBaseName}.mjs-inputFiles.json`;
                try {
                  const stats = fs.statSync(inputFilesPath);
                  fs.utimesSync(inputFilesPath, stats.atime, new Date());
                  console.log(`[NODE BUILDER] Triggered inputFiles.json update from manual rebuild`);
                } catch (error) {
                  console.error(`[NODE BUILDER] Failed to trigger inputFiles.json update:`, error);
                }
              });
            }
          }).catch(error => {
            console.error(`[NODE BUILDER] Manual rebuild failed:`, error);
          });
        }
      });
      
      // Clean up watcher on exit
      process.on('SIGINT', () => {
        watcher.close();
      });
    }
    
    // Keep the process alive indefinitely in dev mode
    // This is important for the container to stay running
    console.log(`[NODE BUILDER] Keeping process alive for continuous watching...`);
    // Use setInterval to keep event loop active
    const keepAliveInterval = setInterval(() => {
      // Just keep the process alive
    }, 60000); // Every minute
    
    process.on('SIGINT', () => {
      clearInterval(keepAliveInterval);
    });
    
  } else {
    // Once mode - just build once
    const buildResult = await esbuild.build(n);
    if (buildResult.metafile) {
      await processMetafile(projectConfig, buildResult.metafile, 'node', testName);
    } else {
      console.warn("No metafile generated by esbuild");
    }
  }
}

async function main() {
  try {
    const nodeConfigs = (await import(nodeConfigPath)).default;
    const projectConfigs = (await import(projectConfigPath)).default;
    await startBundling(nodeConfigs, projectConfigs);
    
    // In dev mode, keep the process running even if there's an error
    const isDevMode = process.env.MODE === 'dev' || process.argv.includes('dev');
    if (isDevMode) {
      // Don't exit on unhandled rejections
      process.on('unhandledRejection', (reason, promise) => {
        console.error('[NODE BUILDER] Unhandled Rejection at:', promise, 'reason:', reason);
      });
      
      process.on('uncaughtException', (error) => {
        console.error('[NODE BUILDER] Uncaught Exception:', error);
      });
      
      // Keep alive
      setInterval(() => {
        console.log('[NODE BUILDER] Still watching for changes...');
      }, 30000);
    }
  } catch (error) {
    console.error("NODE BUILDER: Error:", error);
    
    // In dev mode, don't exit immediately
    const isDevMode = process.env.MODE === 'dev' || process.argv.includes('dev');
    if (isDevMode) {
      console.error('[NODE BUILDER] Error occurred but keeping process alive in dev mode');
      // Keep the process alive to restart watching
      setInterval(() => {}, 1000);
    } else {
      process.exit(1);
    }
  }
}

main();
