// Framework converter interface for Go
package frameworkconverters

import (
	"os"
	"path/filepath"
	"strings"
)

// FrameworkConverter defines the interface for all framework converters
type FrameworkConverter interface {
	Name() string
	Detect(filePath string) bool
	GenerateWrapper(entryPointPath string, detectionResult map[string]interface{}, filesHash string) string
	TranslateToTesteranto(detectionResult map[string]interface{}) map[string]interface{}
}

// Registry of all framework converters
var Converters = []FrameworkConverter{
	&GoTestConverter{},
	&GinkgoConverter{},
	&TestifyConverter{},
	&GenericGoConverter{},
}

// DetectFramework detects which framework a Go test file uses
func DetectFramework(filePath string) FrameworkConverter {
	for _, converter := range Converters {
		if converter.Detect(filePath) {
			return converter
		}
	}
	return &GenericGoConverter{}
}

// GoTestConverter handles standard Go test files
type GoTestConverter struct{}

func (g *GoTestConverter) Name() string {
	return "gotest"
}

func (g *GoTestConverter) Detect(filePath string) bool {
	if !strings.HasSuffix(filePath, ".go") {
		return false
	}
	
	content, err := os.ReadFile(filePath)
	if err != nil {
		return false
	}
	
	contentStr := string(content)
	
	// Check for Go test patterns
	hasTestFunc := strings.Contains(contentStr, "func Test") && 
	              (strings.Contains(contentStr, "testing.T") || strings.Contains(contentStr, "*testing.T"))
	hasTestMain := strings.Contains(contentStr, "func TestMain")
	
	return hasTestFunc || hasTestMain
}

func (g *GoTestConverter) GenerateWrapper(entryPointPath string, detectionResult map[string]interface{}, filesHash string) string {
	absPath, _ := filepath.Abs(entryPointPath)
	
	return `// Go test wrapper generated by testeranto
// Hash: ` + filesHash + `
// Framework: gotest
// This file loads and executes Go tests

package main

import (
	"fmt"
	"os"
	"testing"
)

func main() {
	fmt.Println("Running Go test:", "` + absPath + `")
	
	// In Go, we can't dynamically import test files like in JavaScript
	// Instead, we need to run the tests using the go test command
	// This wrapper will be executed by the Go test runner
	
	// For now, we'll just print a message
	// The actual test execution will be handled by the native Go test runner
	fmt.Println("Test file detected. Use 'go test' to run tests.")
	
	// Exit with success code
	os.Exit(0)
}
`
}

func (g *GoTestConverter) TranslateToTesteranto(detectionResult map[string]interface{}) map[string]interface{} {
	return map[string]interface{}{
		"specification": `// Generated specification for Go tests
const specification = (Suite, Given, When, Then) => [
  Suite("Go Tests", {
    "go-test": Given(
      ["Go test suite"],
      [
        When("run go test", (store) => {
          // Go test execution
          return store;
        })
      ],
      [
        Then("verify go test assertions", async (store) => {
          // Go test assertions
          return store;
        })
      ]
    )
  })
];`,
		"implementation": `// Generated implementation for Go tests
const implementation = {
  suites: {
    Default: "Go test suite"
  },
  givens: {
    Default: () => ({ /* Go test context */ })
  },
  whens: {
    runTest: (testName) => (store) => {
      console.log('Running Go test:', testName);
      return store;
    }
  },
  thens: {
    verify: (expected) => (store) => {
      // Verify Go test assertions
      return store;
    }
  }
};`,
		"adapter": `// Generated adapter for Go tests
const adapter = {
  beforeAll: async (input, testResource) => {
    console.log('Go test beforeAll');
    return input;
  },
  beforeEach: async (subject, initializer, testResource, initialValues) => {
    console.log('Go test beforeEach');
    return subject;
  },
  execute: async (store, actionCB, testResource) => {
    return actionCB(store);
  },
  verify: async (store, checkCB, testResource) => {
    return checkCB(store);
  },
  cleanupEach: async (store, key) => {
    console.log('Go test cleanupEach');
    return store;
  },
  cleanupAll: async (store) => {
    console.log('Go test cleanupAll');
    return store;
  },
  assert: (x) => !!x
};`,
	}
}

// GinkgoConverter handles Ginkgo BDD test files
type GinkgoConverter struct{}

func (g *GinkgoConverter) Name() string {
	return "ginkgo"
}

func (g *GinkgoConverter) Detect(filePath string) bool {
	if !strings.HasSuffix(filePath, ".go") {
		return false
	}
	
	content, err := os.ReadFile(filePath)
	if err != nil {
		return false
	}
	
	contentStr := string(content)
	
	// Check for Ginkgo patterns
	hasGinkgoImport := strings.Contains(contentStr, "github.com/onsi/ginkgo") || 
	                  strings.Contains(contentStr, "github.com/onsi/ginkgo/v2")
	hasGinkgoDescribe := strings.Contains(contentStr, "Describe(") || 
	                     strings.Contains(contentStr, "It(") ||
	                     strings.Contains(contentStr, "BeforeEach(")
	
	return hasGinkgoImport && hasGinkgoDescribe
}

func (g *GinkgoConverter) GenerateWrapper(entryPointPath string, detectionResult map[string]interface{}, filesHash string) string {
	return `// Ginkgo test wrapper generated by testeranto
// Hash: ` + filesHash + `
// Framework: ginkgo
// This file loads and executes Ginkgo tests

package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println("Running Ginkgo test:", "` + entryPointPath + `")
	
	// Ginkgo tests need to be run through the ginkgo CLI
	// This wrapper will be executed by the ginkgo test runner
	
	fmt.Println("Ginkgo test detected. Use 'ginkgo run' to execute tests.")
	
	// Exit with success code
	os.Exit(0)
}
`
}

func (g *GinkgoConverter) TranslateToTesteranto(detectionResult map[string]interface{}) map[string]interface{} {
	return map[string]interface{}{
		"specification": `// Generated specification for Ginkgo tests
const specification = (Suite, Given, When, Then) => [
  Suite("Ginkgo Tests", {
    "ginkgo-test": Given(
      ["Ginkgo BDD test suite"],
      [
        When("run ginkgo test", (store) => {
          // Ginkgo test execution
          return store;
        })
      ],
      [
        Then("verify ginkgo assertions", async (store) => {
          // Ginkgo assertions with gomega
          return store;
        })
      ]
    )
  })
];`,
		"implementation": `// Generated implementation for Ginkgo tests
const implementation = {
  suites: {
    Default: "Ginkgo test suite"
  },
  givens: {
    Default: () => ({ /* Ginkgo test context */ })
  },
  whens: {
    runTest: (testName) => (store) => {
      console.log('Running Ginkgo test:', testName);
      return store;
    }
  },
  thens: {
    verify: (expected) => (store) => {
      // Verify Ginkgo assertions
      return store;
    }
  }
};`,
		"adapter": `// Generated adapter for Ginkgo tests
const adapter = {
  beforeAll: async (input, testResource) => {
    console.log('Ginkgo BeforeSuite');
    return input;
  },
  beforeEach: async (subject, initializer, testResource, initialValues) => {
    console.log('Ginkgo BeforeEach');
    return subject;
  },
  execute: async (store, actionCB, testResource) => {
    return actionCB(store);
  },
  verify: async (store, checkCB, testResource) => {
    return checkCB(store);
  },
  cleanupEach: async (store, key) => {
    console.log('Ginkgo AfterEach');
    return store;
  },
  cleanupAll: async (store) => {
    console.log('Ginkgo AfterSuite');
    return store;
  },
  assert: (x) => !!x
};`,
	}
}

// TestifyConverter handles Testify test files
type TestifyConverter struct{}

func (t *TestifyConverter) Name() string {
	return "testify"
}

func (t *TestifyConverter) Detect(filePath string) bool {
	if !strings.HasSuffix(filePath, ".go") {
		return false
	}
	
	content, err := os.ReadFile(filePath)
	if err != nil {
		return false
	}
	
	contentStr := string(content)
	
	// Check for Testify patterns
	hasTestifyImport := strings.Contains(contentStr, "github.com/stretchr/testify") || 
	                   strings.Contains(contentStr, "github.com/stretchr/testify/assert") ||
	                   strings.Contains(contentStr, "github.com/stretchr/testify/require")
	hasTestifyAssert := strings.Contains(contentStr, "assert.") || 
	                   strings.Contains(contentStr, "require.")
	
	return hasTestifyImport && hasTestifyAssert
}

func (t *TestifyConverter) GenerateWrapper(entryPointPath string, detectionResult map[string]interface{}, filesHash string) string {
	return `// Testify test wrapper generated by testeranto
// Hash: ` + filesHash + `
// Framework: testify
// This file loads and executes Testify tests

package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println("Running Testify test:", "` + entryPointPath + `")
	
	// Testify tests are standard Go tests with assertion helpers
	// They can be run with 'go test'
	
	fmt.Println("Testify test detected. Use 'go test' to run tests.")
	
	// Exit with success code
	os.Exit(0)
}
`
}

func (t *TestifyConverter) TranslateToTesteranto(detectionResult map[string]interface{}) map[string]interface{} {
	return map[string]interface{}{
		"specification": `// Generated specification for Testify tests
const specification = (Suite, Given, When, Then) => [
  Suite("Testify Tests", {
    "testify-test": Given(
      ["Testify assertion test suite"],
      [
        When("run testify test", (store) => {
          // Testify test execution
          return store;
        })
      ],
      [
        Then("verify testify assertions", async (store) => {
          // Testify assertions with assert/require
          return store;
        })
      ]
    )
  })
];`,
		"implementation": `// Generated implementation for Testify tests
const implementation = {
  suites: {
    Default: "Testify test suite"
  },
  givens: {
    Default: () => ({ /* Testify test context */ })
  },
  whens: {
    runTest: (testName) => (store) => {
      console.log('Running Testify test:', testName);
      return store;
    }
  },
  thens: {
    verify: (expected) => (store) => {
      // Verify Testify assertions
      return store;
    }
  }
};`,
		"adapter": `// Generated adapter for Testify tests
const adapter = {
  beforeAll: async (input, testResource) => {
    console.log('Testify setup');
    return input;
  },
  beforeEach: async (subject, initializer, testResource, initialValues) => {
    console.log('Testify beforeEach');
    return subject;
  },
  execute: async (store, actionCB, testResource) => {
    return actionCB(store);
  },
  verify: async (store, checkCB, testResource) => {
    return checkCB(store);
  },
  cleanupEach: async (store, key) => {
    console.log('Testify cleanupEach');
    return store;
  },
  cleanupAll: async (store) => {
    console.log('Testify cleanupAll');
    return store;
  },
  assert: (x) => !!x
};`,
	}
}

// GenericGoConverter is a fallback converter for Go files
type GenericGoConverter struct{}

func (g *GenericGoConverter) Name() string {
	return "generic-go"
}

func (g *GenericGoConverter) Detect(filePath string) bool {
	return strings.HasSuffix(filePath, ".go")
}

func (g *GenericGoConverter) GenerateWrapper(entryPointPath string, detectionResult map[string]interface{}, filesHash string) string {
	return `// Generic Go test wrapper generated by testeranto
// Hash: ` + filesHash + `
// Framework: generic-go
// This file loads Go source files

package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println("Processing Go file:", "` + entryPointPath + `")
	
	// Generic Go file - could be source code or tests
	// We'll just compile and run it if it's a main package
	
	fmt.Println("Go file processed successfully.")
	
	// Exit with success code
	os.Exit(0)
}
`
}

func (g *GenericGoConverter) TranslateToTesteranto(detectionResult map[string]interface{}) map[string]interface{} {
	return map[string]interface{}{
		"specification": `// Generated specification for generic Go tests
const specification = (Suite, Given, When, Then) => [
  Suite("Generic Go Tests", {
    "generic-test": Given(
      ["Generic Go test suite"],
      [
        When("run generic test", (store) => {
          // Generic test execution
          return store;
        })
      ],
      [
        Then("verify generic assertions", async (store) => {
          // Generic assertions
          return store;
        })
      ]
    )
  })
];`,
		"implementation": `// Generated implementation for generic Go tests
const implementation = {
  suites: {
    Default: "Generic Go test suite"
  },
  givens: {
    Default: () => ({ /* Generic test context */ })
  },
  whens: {
    runTest: (testName) => (store) => {
      console.log('Running generic Go test:', testName);
      return store;
    }
  },
  thens: {
    verify: (expected) => (store) => {
      // Verify generic assertions
      return store;
    }
  }
};`,
		"adapter": `// Generated adapter for generic Go tests
const adapter = {
  beforeAll: async (input, testResource) => {
    console.log('Generic Go beforeAll');
    return input;
  },
  beforeEach: async (subject, initializer, testResource, initialValues) => {
    console.log('Generic Go beforeEach');
    return subject;
  },
  execute: async (store, actionCB, testResource) => {
    return actionCB(store);
  },
  verify: async (store, checkCB, testResource) => {
    return checkCB(store);
  },
  cleanupEach: async (store, key) => {
    console.log('Generic Go cleanupEach');
    return store;
  },
  cleanupAll: async (store) => {
    console.log('Generic Go cleanupAll');
    return store;
  },
  assert: (x) => !!x
};`,
	}
}
