services:
  nodetests-builder:
    container_name: "nodetests-builder"
    environment:
      NODE_ENV: production
      ENV: node
      MODE: dev
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/dist:/workspace/dist"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx /workspace/testeranto/node_runtime.ts /workspace/testeranto/testeranto.ts /workspace/testeranto/runtimes/node/node.mjs '{\"name\":\"nodetests\",\"tests\":[\"src/lib/tiposkripto/tests/abstractBase.test/index.ts\",\"src/lib/tiposkripto/tests/calculator/Calculator.test.node.ts\",\"src/lib/tiposkripto/tests/circle/Circle.test.ts\",\"src/lib/tiposkripto/tests/Rectangle/Rectangle.test.ts\"],\"outputs\":[]}'"
    networks:
      - allTests_network
    restart: no
    image: "testeranto-node-nodetests:latest"
    extra_hosts:
      host.docker.internal: "host-gateway"
  webtests-builder:
    container_name: "webtests-builder"
    environment:
      NODE_ENV: production
      ENV: web
      MODE: dev
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/dist:/workspace/dist"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx /workspace/testeranto/web_runtime.ts /workspace/testeranto/testeranto.ts /workspace/testeranto/runtimes/web/web.mjs '{\"name\":\"webtests\",\"tests\":[\"src/lib/tiposkripto/tests/calculator/Calculator.test.web.ts\",\"src/lib/tiposkripto/tests/calculator/Calculator.test.web.react.ts\"],\"outputs\":[]}'"
    networks:
      - allTests_network
    restart: no
    image: "testeranto-web-webtests:latest"
    extra_hosts:
      host.docker.internal: "host-gateway"
  javatests-builder:
    container_name: "javatests-builder"
    environment:
      NODE_ENV: production
      ENV: java
      MODE: dev
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/dist:/workspace/dist"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx /workspace/testeranto/node_runtime.ts /workspace/testeranto/testeranto.ts /workspace/testeranto/runtimes/node/node.mjs '{\"name\":\"javatests\",\"tests\":[\"src/java/test/java/com/example/calculator/CalculatorTest.java\"],\"outputs\":[\"src/lib/kafe/examples/calculator/Calculator.java\"]}'"
    networks:
      - allTests_network
    restart: no
    image: "testeranto-java-javatests:latest"
    extra_hosts:
      host.docker.internal: "host-gateway"
  rubytests-builder:
    container_name: "rubytests-builder"
    environment:
      NODE_ENV: production
      ENV: ruby
      MODE: dev
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/dist:/workspace/dist"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "ruby /workspace/testeranto/ruby_runtime.rb /workspace/testeranto/testeranto.ts /workspace/testeranto/runtimes/ruby/ruby.rb '{\"name\":\"rubytests\",\"tests\":[\"src/lib/rubeno/examples/calculator/Calculator.test.rb\"],\"outputs\":[\"test_output\",\"testeranto/reports/rubytests\"]}'"
    networks:
      - allTests_network
    restart: no
    image: "testeranto-ruby-rubytests:latest"
    extra_hosts:
      host.docker.internal: "host-gateway"
  pythontests-builder:
    container_name: "pythontests-builder"
    environment:
      NODE_ENV: production
      ENV: python
      MODE: dev
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/dist:/workspace/dist"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "python3 /workspace/testeranto/python_runtime.py /workspace/testeranto/testeranto.ts /workspace/testeranto/runtimes/python/python.mjs '{\"name\":\"pythontests\",\"tests\":[\"src/lib/pitono/examples/calculator_test.py\"],\"outputs\":[\"testeranto/reports/pythontests\"]}'"
    networks:
      - allTests_network
    restart: no
    image: "testeranto-python-pythontests:latest"
    extra_hosts:
      host.docker.internal: "host-gateway"
  nodetests-src_lib_tiposkripto_tests_abstractbase-test_index-ts-bdd:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/node/node.Dockerfile
    container_name: "nodetests-src_lib_tiposkripto_tests_abstractbase-test_index-ts-bdd"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx testeranto/bundles/nodetests/src/lib/tiposkripto/tests/abstractBase.test/index.mjs '{\"name\":\"node-test\",\"ports\":[1111],\"fs\":\"testeranto/reports/nodetests/src/lib/tiposkripto/tests/abstractBase.test/index.mjs/\",\"timeout\":30000,\"retries\":0,\"environment\":{}}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  nodetests-src_lib_tiposkripto_tests_calculator_calculator-test-node-ts-bdd:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/node/node.Dockerfile
    container_name: "nodetests-src_lib_tiposkripto_tests_calculator_calculator-test-node-ts-bdd"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx testeranto/bundles/nodetests/src/lib/tiposkripto/tests/calculator/Calculator.test.node.mjs '{\"name\":\"node-test\",\"ports\":[1111],\"fs\":\"testeranto/reports/nodetests/src/lib/tiposkripto/tests/calculator/Calculator.test.node.mjs/\",\"timeout\":30000,\"retries\":0,\"environment\":{}}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  nodetests-src_lib_tiposkripto_tests_circle_circle-test-ts-bdd:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/node/node.Dockerfile
    container_name: "nodetests-src_lib_tiposkripto_tests_circle_circle-test-ts-bdd"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx testeranto/bundles/nodetests/src/lib/tiposkripto/tests/circle/Circle.test.mjs '{\"name\":\"node-test\",\"ports\":[1111],\"fs\":\"testeranto/reports/nodetests/src/lib/tiposkripto/tests/circle/Circle.test.mjs/\",\"timeout\":30000,\"retries\":0,\"environment\":{}}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  nodetests-src_lib_tiposkripto_tests_rectangle_rectangle-test-ts-bdd:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/node/node.Dockerfile
    container_name: "nodetests-src_lib_tiposkripto_tests_rectangle_rectangle-test-ts-bdd"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx testeranto/bundles/nodetests/src/lib/tiposkripto/tests/Rectangle/Rectangle.test.mjs '{\"name\":\"node-test\",\"ports\":[1111],\"fs\":\"testeranto/reports/nodetests/src/lib/tiposkripto/tests/Rectangle/Rectangle.test.mjs/\",\"timeout\":30000,\"retries\":0,\"environment\":{}}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  webtests-src_lib_tiposkripto_tests_calculator_calculator-test-web-ts-bdd:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/web/web.Dockerfile
    container_name: "webtests-src_lib_tiposkripto_tests_calculator_calculator-test-web-ts-bdd"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx /workspace/testeranto/web_hoist.ts testeranto/bundles/webtests/src/lib/tiposkripto/tests/calculator/Calculator.test.web.mjs '{\"name\":\"web-test\",\"ports\":[1111],\"fs\":\"testeranto/reports/webtests/src/lib/tiposkripto/tests/calculator/Calculator.test.web.mjs/\",\"timeout\":30000,\"retries\":0,\"environment\":{}}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  webtests-src_lib_tiposkripto_tests_calculator_calculator-test-web-ts-check-0:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/web/web.Dockerfile
    container_name: "webtests-src_lib_tiposkripto_tests_calculator_calculator-test-web-ts-check-0"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx testeranto/bundles/webtests/src/lib/tiposkripto/tests/calculator/Calculator.test.web.ts_check_0.mjs '{\"ports\":[1111],\"fs\":\"testeranto/reports/webtests/src/lib/tiposkripto/tests/calculator/Calculator.test.web.ts/\"}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  webtests-src_lib_tiposkripto_tests_calculator_calculator-test-web-ts-check-1:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/web/web.Dockerfile
    container_name: "webtests-src_lib_tiposkripto_tests_calculator_calculator-test-web-ts-check-1"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx testeranto/bundles/webtests/src/lib/tiposkripto/tests/calculator/Calculator.test.web.ts_check_1.mjs '{\"ports\":[1111],\"fs\":\"testeranto/reports/webtests/src/lib/tiposkripto/tests/calculator/Calculator.test.web.ts/\"}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  webtests-src_lib_tiposkripto_tests_calculator_calculator-test-web-react-ts-bdd:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/web/web.Dockerfile
    container_name: "webtests-src_lib_tiposkripto_tests_calculator_calculator-test-web-react-ts-bdd"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx /workspace/testeranto/web_hoist.ts testeranto/bundles/webtests/src/lib/tiposkripto/tests/calculator/Calculator.test.web.react.mjs '{\"name\":\"web-test\",\"ports\":[1111],\"fs\":\"testeranto/reports/webtests/src/lib/tiposkripto/tests/calculator/Calculator.test.web.react.mjs/\",\"timeout\":30000,\"retries\":0,\"environment\":{}}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  webtests-src_lib_tiposkripto_tests_calculator_calculator-test-web-react-ts-check-0:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/web/web.Dockerfile
    container_name: "webtests-src_lib_tiposkripto_tests_calculator_calculator-test-web-react-ts-check-0"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx testeranto/bundles/webtests/src/lib/tiposkripto/tests/calculator/Calculator.test.web.react.ts_check_0.mjs '{\"ports\":[1111],\"fs\":\"testeranto/reports/webtests/src/lib/tiposkripto/tests/calculator/Calculator.test.web.react.ts/\"}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  webtests-src_lib_tiposkripto_tests_calculator_calculator-test-web-react-ts-check-1:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/web/web.Dockerfile
    container_name: "webtests-src_lib_tiposkripto_tests_calculator_calculator-test-web-react-ts-check-1"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx testeranto/bundles/webtests/src/lib/tiposkripto/tests/calculator/Calculator.test.web.react.ts_check_1.mjs '{\"ports\":[1111],\"fs\":\"testeranto/reports/webtests/src/lib/tiposkripto/tests/calculator/Calculator.test.web.react.ts/\"}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  javatests-src_java_test_java_com_example_calculator_calculatortest-java-bdd:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/java/java.Dockerfile
    container_name: "javatests-src_java_test_java_com_example_calculator_calculatortest-java-bdd"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx testeranto/bundles/javatests/src/java/test/java/com/example/calculator/CalculatorTest.java '{\"name\":\"java-test\",\"ports\":[1111],\"fs\":\"testeranto/reports/javatests/src/java/test/java/com/example/calculator/CalculatorTest.java/\",\"timeout\":30000,\"retries\":0,\"environment\":{}}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  javatests-src_java_test_java_com_example_calculator_calculatortest-java-check-0:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/java/java.Dockerfile
    container_name: "javatests-src_java_test_java_com_example_calculator_calculatortest-java-check-0"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx testeranto/bundles/javatests/src/java/test/java/com/example/calculator/CalculatorTest.java_check_0.java '{\"ports\":[1111],\"fs\":\"testeranto/reports/javatests/src/java/test/java/com/example/calculator/CalculatorTest.java/\"}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  javatests-src_java_test_java_com_example_calculator_calculatortest-java-check-1:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/java/java.Dockerfile
    container_name: "javatests-src_java_test_java_com_example_calculator_calculatortest-java-check-1"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx testeranto/bundles/javatests/src/java/test/java/com/example/calculator/CalculatorTest.java_check_1.java '{\"ports\":[1111],\"fs\":\"testeranto/reports/javatests/src/java/test/java/com/example/calculator/CalculatorTest.java/\"}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  rubytests-src_lib_rubeno_examples_calculator_calculator-test-rb-bdd:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/ruby/ruby.Dockerfile
    container_name: "rubytests-src_lib_rubeno_examples_calculator_calculator-test-rb-bdd"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "ruby testeranto/bundles/rubytests/src/lib/rubeno/examples/calculator/Calculator.test.rb '{\"name\":\"ruby-test\",\"ports\":[1111],\"fs\":\"testeranto/reports/rubytests/src/lib/rubeno/examples/calculator/Calculator.test.rb/\",\"timeout\":30000,\"retries\":0,\"environment\":{}}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  pythontests-src_lib_pitono_examples_calculator_test-py-bdd:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/python/python.Dockerfile
    container_name: "pythontests-src_lib_pitono_examples_calculator_test-py-bdd"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "python3 testeranto/bundles/pythontests/src/lib/pitono/examples/calculator_test.py '{\"name\":\"python-test\",\"ports\":[1111],\"fs\":\"testeranto/reports/pythontests/src/lib/pitono/examples/calculator_test.py/\",\"timeout\":30000,\"retries\":0,\"environment\":{}}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  pythontests-src_lib_pitono_examples_calculator_test-py-check-0:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/python/python.Dockerfile
    container_name: "pythontests-src_lib_pitono_examples_calculator_test-py-check-0"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "python3 testeranto/bundles/pythontests/src/lib/pitono/examples/calculator_test.py_check_0.py '{\"ports\":[1111],\"fs\":\"testeranto/reports/pythontests/src/lib/pitono/examples/calculator_test.py/\"}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  pythontests-src_lib_pitono_examples_calculator_test-py-check-1:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/python/python.Dockerfile
    container_name: "pythontests-src_lib_pitono_examples_calculator_test-py-check-1"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "python3 testeranto/bundles/pythontests/src/lib/pitono/examples/calculator_test.py_check_1.py '{\"ports\":[1111],\"fs\":\"testeranto/reports/pythontests/src/lib/pitono/examples/calculator_test.py/\"}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  pythontests-src_lib_pitono_examples_calculator_test-py-check-2:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/python/python.Dockerfile
    container_name: "pythontests-src_lib_pitono_examples_calculator_test-py-check-2"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "python3 testeranto/bundles/pythontests/src/lib/pitono/examples/calculator_test.py_check_2.py '{\"ports\":[1111],\"fs\":\"testeranto/reports/pythontests/src/lib/pitono/examples/calculator_test.py/\"}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"
  chrome:
    image: "browserless/chrome:latest"
    container_name: "chrome-service"
    environment:
      CONNECTION_TIMEOUT: 60000
      MAX_CONCURRENT_SESSIONS: 1
      ENABLE_CORS: true
      PREBOOT_CHROME: true
      DEFAULT_BLOCK_ADS: true
    shm_size: 2g
    expose:
      - 3000
    ports:
      - "9222:3000"
    networks:
      - allTests_network

networks:
  allTests_network:
    driver: bridge