services:
  nodetests-builder:
    container_name: "nodetests-builder"
    environment:
      NODE_ENV: production
      ENV: node
      MODE: dev
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/dist:/workspace/dist"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx /workspace/testeranto/node_runtime.ts /workspace/testeranto/testeranto.ts /workspace/testeranto/runtimes/node/node.mjs '{\"name\":\"nodetests\",\"tests\":[\"src/lib/tiposkripto/tests/calculator/Calculator.test.node.ts\"],\"outputs\":[]}'"
    networks:
      - allTests_network
    restart: no
    image: "testeranto-node-nodetests:latest"
    extra_hosts:
      host.docker.internal: "host-gateway"
  nodetests-src_lib_tiposkripto_tests_calculator_calculator-test-node-ts-bdd:
    build:
      context: /Users/adam/Code/testeranto
      dockerfile: testeranto/runtimes/node/node.Dockerfile
    container_name: "nodetests-src_lib_tiposkripto_tests_calculator_calculator-test-node-ts-bdd"
    working_dir: /workspace
    volumes:
      - "/Users/adam/Code/testeranto/src:/workspace/src"
      - "/Users/adam/Code/testeranto/test:/workspace/test"
      - "/Users/adam/Code/testeranto/SOUL.md:/workspace/SOUL.md"
      - "/Users/adam/Code/testeranto/testeranto:/workspace/testeranto"
    command: "yarn tsx testeranto/bundles/nodetests/src/lib/tiposkripto/tests/calculator/Calculator.test.node.mjs '{\"ports\":[1111],\"fs\":\"testeranto/reports/nodetests/src/lib/tiposkripto/tests/calculator/Calculator.test.node.ts/\"}'"
    networks:
      - allTests_network
    restart: no
    extra_hosts:
      host.docker.internal: "host-gateway"

networks:
  allTests_network:
    driver: bridge