// This file is no longer needed since each view has its own bundle
// The bundle generated by the server includes everything needed
// We keep it as a minimal stub to avoid breaking existing code
if (typeof window !== 'undefined') {
  (window as any).TesterantoViews = {
    renderView: function(viewKey: string, rootElement: HTMLElement, dataPath: string) {
      console.warn('TesterantoViews.renderView is deprecated. Views should use their own bundles.');
      const div = document.createElement('div');
      div.innerHTML = `
        <div style="padding: 40px; text-align: center; border: 1px solid #ccc; border-radius: 8px; background-color: #fafafa;">
          <h2>View: ${viewKey}</h2>
          <p>This view should be loaded via its own bundle.</p>
          <p>If you see this message, the view bundle may not have been generated correctly.</p>
          <p>Data path: ${dataPath}</p>
        </div>
      `;
      rootElement.appendChild(div);
    }
  };
}
