//! AST Transformer for Rust tests
//! Transforms native Rust tests to Testeranto-compatible tests

use syn::{parse_file, Item};
use quote::{quote, ToTokens};
use std::fs;

/// AST Transformer for Rust tests
pub struct RustASTTransformer;

impl RustASTTransformer {
    /// Parse a Rust file and transform test functions to Testeranto format
    pub fn transform_file(file_path: &str) -> Result<String, String> {
        // Read the source file
        let source = fs::read_to_string(file_path)
            .map_err(|e| format!("Failed to read file {}: {}", file_path, e))?;
        
        // Parse the file
        let ast = parse_file(&source)
            .map_err(|e| format!("Failed to parse Rust file {}: {}", file_path, e))?;
        
        // Extract test information
        let test_info = Self::extract_test_info(&ast);
        
        // Generate Testeranto-compatible code
        let output = Self::generate_testeranto_code(&test_info, file_path);
        
        Ok(output)
    }
    
    /// Extract test information from AST
    fn extract_test_info(file: &syn::File) -> Vec<TestInfo> {
        let mut tests = Vec::new();
        
        for item in &file.items {
            if let Item::Fn(func) = item {
                // Check if this is a test function
                let is_test = func.attrs.iter().any(|attr| {
                    attr.path().is_ident("test") || 
                    attr.path().is_ident("tokio::test") ||
                    attr.path().is_ident("async_std::test")
                });
                
                if is_test {
                    let test_name = func.sig.ident.to_string();
                    let is_async = func.sig.asyncness.is_some();
                    let body = func.block.to_token_stream().to_string();
                    
                    tests.push(TestInfo {
                        name: test_name,
                        body,
                        is_async,
                        attributes: func.attrs.iter()
                            .map(|attr| attr.to_token_stream().to_string())
                            .collect(),
                    });
                }
            }
        }
        
        tests
    }
    
    /// Generate Testeranto-compatible code from test information
    fn generate_testeranto_code(tests: &[TestInfo], _file_path: &str) -> String {
        if tests.is_empty() {
            return "// No tests found in file".to_string();
        }
        
        // Generate test cases
        let test_cases: Vec<_> = tests.iter().map(|test| {
            let name = &test.name;
            let async_keyword = if test.is_async { "async " } else { "" };
            
            quote! {
                // Test: #name
                // Original test transformed to Testeranto format
                // This is a placeholder - in a full implementation, we would
                // parse the test body and convert assertions to Testeranto format
                #async_keyword fn #name() -> Result<(), Box<dyn std::error::Error>> {
                    // TODO: Transform test body to Testeranto assertions
                    Ok(())
                }
            }
        }).collect();
        
        // Generate the complete output
        let output = quote! {
            // Generated by Testeranto AST Transformer
            
            // Import Testeranto
            use rusto::prelude::*;
            
            // Test functions
            #(#test_cases)*
            
            // Main test suite
            pub fn test_suite() -> rusto::Rusto<impl rusto::IbddInAny, impl rusto::IbddOutAny, ()> {
                // TODO: Create actual Testeranto test suite
                // This would involve creating specification, implementation, and adapter
                unimplemented!("Full Testeranto suite generation not yet implemented")
            }
        };
        
        output.to_string()
    }
    
    /// Simple detection of test functions
    pub fn detect_tests(file_path: &str) -> Result<Vec<String>, String> {
        let source = fs::read_to_string(file_path)
            .map_err(|e| format!("Failed to read file {}: {}", file_path, e))?;
        
        let ast = parse_file(&source)
            .map_err(|e| format!("Failed to parse Rust file {}: {}", file_path, e))?;
        
        let mut test_names = Vec::new();
        
        for item in ast.items {
            if let Item::Fn(func) = item {
                if func.attrs.iter().any(|attr| attr.path().is_ident("test")) {
                    test_names.push(func.sig.ident.to_string());
                }
            }
        }
        
        Ok(test_names)
    }
}

/// Information about a test function
#[derive(Debug)]
pub struct TestInfo {
    pub name: String,
    pub body: String,
    pub is_async: bool,
    pub attributes: Vec<String>,
}
