//! Interoperability module for bidirectional test transformation in Rust
//! 
//! This module provides interfaces for converting between Rusto tests and
//! other Rust test frameworks.

use std::collections::HashMap;
use std::fs;
use syn::{parse_file, File};
use quote::ToTokens;

/// Core interoperability trait for Rust test frameworks
pub trait RustTestInteroperability {
    /// Import tests from an external Rust framework to Rusto
    fn import_to_rusto(&self, source_path: &str, framework: &str) -> Result<String, String>;
    
    /// Export Rusto tests to an external Rust framework
    fn export_from_rusto(&self, source_path: &str, target_framework: &str) -> Result<String, String>;
    
    /// Create a bidirectional pairing between Rusto and framework tests
    fn create_pairing(&self, source_path: &str) -> Result<HashMap<String, String>, String>;
    
    /// Get supported Rust frameworks for import
    fn supported_import_frameworks(&self) -> Vec<&'static str>;
    
    /// Get supported Rust frameworks for export
    fn supported_export_frameworks(&self) -> Vec<&'static str>;
}

/// Rust-specific framework configuration
#[derive(Debug, Clone)]
pub struct RustFrameworkConfig {
    pub name: &'static str,
    pub import_supported: bool,
    pub export_supported: bool,
    pub detection_patterns: Vec<&'static str>,
}

/// Main interoperability implementation for Rust
pub struct RustInteroperability;

impl RustInteroperability {
    pub fn new() -> Self {
        Self
    }
    
    /// Detect the Rust test framework from file content
    pub fn detect_rust_framework(&self, file_path: &str) -> Result<String, String> {
        let content = fs::read_to_string(file_path)
            .map_err(|e| format!("Failed to read file: {}", e))?;
        
        // Check for Rust test patterns
        if content.contains("#[test]") || content.contains("#[tokio::test]") || content.contains("#[async_std::test]") {
            return Ok("rust_test".to_string());
        }
        
        if content.contains("criterion") && (content.contains("criterion_group") || content.contains("criterion::")) {
            return Ok("criterion".to_string());
        }
        
        if content.contains("proptest") && content.contains("proptest!") {
            return Ok("proptest".to_string());
        }
        
        if content.contains("rstest") && content.contains("#[rstest]") {
            return Ok("rstest".to_string());
        }
        
        Err("Could not detect Rust test framework".to_string())
    }
    
    /// Parse Rust file and extract test information
    fn parse_rust_file(&self, file_path: &str) -> Result<File, String> {
        let content = fs::read_to_string(file_path)
            .map_err(|e| format!("Failed to read file: {}", e))?;
        
        parse_file(&content)
            .map_err(|e| format!("Failed to parse Rust file: {}", e))
    }
    
    /// Convert Rust #[test] functions to Rusto format
    fn convert_rust_test_to_rusto(&self, ast: &File, file_path: &str) -> Result<String, String> {
        let mut rusto_tests = Vec::new();
        
        for item in &ast.items {
            if let syn::Item::Fn(func) = item {
                // Check if it's a test function
                let is_test = func.attrs.iter().any(|attr| {
                    attr.path().is_ident("test") || 
                    attr.path().is_ident("tokio::test") ||
                    attr.path().is_ident("async_std::test")
                });
                
                if is_test {
                    let test_name = &func.sig.ident;
                    
                    rusto_tests.push(format!(
                        "// Converted from Rust #[test]: {}\n\
                        rusto::test_suite!(\"{}\", {{\n\
                            // Test implementation would go here\n\
                        }});",
                        test_name, test_name
                    ));
                }
            }
        }
        
        if rusto_tests.is_empty() {
            return Err("No test functions found in file".to_string());
        }
        
        let output = format!(
            "// Generated by Rusto Interoperability\n\
            // Source: {}\n\
            // Framework: rust_test\n\n\
            use rusto::prelude::*;\n\n\
            {}\n",
            file_path,
            rusto_tests.join("\n\n")
        );
        
        Ok(output)
    }
    
    /// Convert Rusto tests to Rust #[test] functions
    fn convert_rusto_to_rust_test(&self, ast: &File, file_path: &str) -> Result<String, String> {
        let mut rust_tests = Vec::new();
        
        // Look for Rusto patterns
        for item in &ast.items {
            if let syn::Item::Fn(func) = item {
                let func_name = func.sig.ident.to_string();
                let func_str = func.to_token_stream().to_string();
                
                // Check if this looks like a Rusto test function
                if func_str.contains("rusto::") || func_str.contains("test_suite!") {
                    rust_tests.push(format!(
                        "#[test]\n\
                        fn {}() {{\n\
                            // Converted from Rusto\n\
                            // Original: {}\n\
                            todo!(\"Implement converted test\");\n\
                        }}",
                        func_name, func_name
                    ));
                }
            }
        }
        
        if rust_tests.is_empty() {
            return Err("No Rusto test patterns found in file".to_string());
        }
        
        let output = format!(
            "// Generated by Rusto Interoperability\n\
            // Source: {}\n\
            // Target: rust_test\n\n\
            {}\n",
            file_path,
            rust_tests.join("\n\n")
        );
        
        Ok(output)
    }
}

impl RustTestInteroperability for RustInteroperability {
    fn import_to_rusto(&self, source_path: &str, framework: &str) -> Result<String, String> {
        let ast = self.parse_rust_file(source_path)?;
        
        match framework {
            "rust_test" => self.convert_rust_test_to_rusto(&ast, source_path),
            "criterion" => {
                // Placeholder for criterion conversion
                Ok(format!(
                    "// Criterion benchmark conversion not yet fully implemented\n\
                    // Source: {}\n\
                    use rusto::prelude::*;\n",
                    source_path
                ))
            },
            _ => Err(format!("Unsupported framework for import: {}", framework)),
        }
    }
    
    fn export_from_rusto(&self, source_path: &str, target_framework: &str) -> Result<String, String> {
        let ast = self.parse_rust_file(source_path)?;
        
        match target_framework {
            "rust_test" => self.convert_rusto_to_rust_test(&ast, source_path),
            "criterion" => {
                // Placeholder for criterion export
                Ok(format!(
                    "// Rusto to Criterion conversion not yet fully implemented\n\
                    // Source: {}\n",
                    source_path
                ))
            },
            _ => Err(format!("Unsupported framework for export: {}", target_framework)),
        }
    }
    
    fn create_pairing(&self, source_path: &str) -> Result<HashMap<String, String>, String> {
        let ast = self.parse_rust_file(source_path)?;
        let mut pairing = HashMap::new();
        
        for item in &ast.items {
            if let syn::Item::Fn(func) = item {
                let func_name = func.sig.ident.to_string();
                let func_str = func.to_token_stream().to_string();
                
                // Check if it's a Rust test
                let is_rust_test = func.attrs.iter().any(|attr| {
                    attr.path().is_ident("test") || 
                    attr.path().is_ident("tokio::test") ||
                    attr.path().is_ident("async_std::test")
                });
                
                // Check if it's a Rusto test
                let is_rusto_test = func_str.contains("rusto::") || func_str.contains("test_suite!");
                
                if is_rust_test {
                    pairing.insert(
                        format!("rust_test:{}", func_name),
                        format!("rusto:{}", func_name)
                    );
                }
                
                if is_rusto_test {
                    pairing.insert(
                        format!("rusto:{}", func_name),
                        format!("rust_test:{}", func_name)
                    );
                }
            }
        }
        
        Ok(pairing)
    }
    
    fn supported_import_frameworks(&self) -> Vec<&'static str> {
        vec!["rust_test", "criterion", "proptest", "rstest"]
    }
    
    fn supported_export_frameworks(&self) -> Vec<&'static str> {
        vec!["rust_test", "criterion"]
    }
}

/// Registry of Rust test frameworks
pub struct RustFrameworkRegistry {
    frameworks: HashMap<String, RustFrameworkConfig>,
}

impl RustFrameworkRegistry {
    pub fn new() -> Self {
        let mut frameworks = HashMap::new();
        
        frameworks.insert("rust_test".to_string(), RustFrameworkConfig {
            name: "rust_test",
            import_supported: true,
            export_supported: true,
            detection_patterns: vec!["#[test]", "#[tokio::test]", "#[async_std::test]"],
        });
        
        frameworks.insert("criterion".to_string(), RustFrameworkConfig {
            name: "criterion",
            import_supported: true,
            export_supported: true,
            detection_patterns: vec!["criterion_group", "criterion::"],
        });
        
        frameworks.insert("proptest".to_string(), RustFrameworkConfig {
            name: "proptest",
            import_supported: false,  // Not yet implemented
            export_supported: false,
            detection_patterns: vec!["proptest!", "proptest::"],
        });
        
        frameworks.insert("rstest".to_string(), RustFrameworkConfig {
            name: "rstest",
            import_supported: false,  // Not yet implemented
            export_supported: false,
            detection_patterns: vec!["#[rstest]"],
        });
        
        Self { frameworks }
    }
    
    pub fn get_framework(&self, name: &str) -> Option<&RustFrameworkConfig> {
        self.frameworks.get(name)
    }
    
    pub fn list_frameworks(&self) -> Vec<&RustFrameworkConfig> {
        self.frameworks.values().collect()
    }
}

/// Utility functions for Rust test interoperability
pub mod utils {
    use super::*;
    
    /// Check if a file contains Rust tests
    pub fn has_rust_tests(file_path: &str) -> Result<bool, String> {
        let content = fs::read_to_string(file_path)
            .map_err(|e| format!("Failed to read file: {}", e))?;
        
        Ok(content.contains("#[test]") || 
           content.contains("#[tokio::test]") || 
           content.contains("#[async_std::test]"))
    }
    
    /// Extract test names from a Rust file
    pub fn extract_test_names(file_path: &str) -> Result<Vec<String>, String> {
        let ast = parse_rust_file(file_path)?;
        let mut test_names = Vec::new();
        
        for item in ast.items {
            if let syn::Item::Fn(func) = item {
                if func.attrs.iter().any(|attr| attr.path().is_ident("test")) {
                    test_names.push(func.sig.ident.to_string());
                }
            }
        }
        
        Ok(test_names)
    }
    
    fn parse_rust_file(file_path: &str) -> Result<File, String> {
        let content = fs::read_to_string(file_path)
            .map_err(|e| format!("Failed to read file: {}", e))?;
        
        parse_file(&content)
            .map_err(|e| format!("Failed to parse Rust file: {}", e))
    }
}
