
import esbuild from "esbuild";
import puppeteer from "puppeteer-core";
import configer from "./esbuild";
import { processMetafile } from "../common";
import * as fs from "fs";
import * as path from "path";
import type { ITestconfigV2 } from "../../../Types";

console.log(process.cwd())
const urlDomain = `http://webtests:8000/`;

const projectConfigPath = process.argv[2];
const nodeConfigPath = process.argv[3];
const testName = process.argv[4];

async function startBundling(
  webConfigs: any,
  projectConfig: ITestconfigV2
) {
  console.log(`[WEB BUILDER] is now bundling: ${testName}`);

  // Validate config
  // if (!config) {
  //   throw new Error('Config is undefined');
  // }
  // if (!config.buildDir) {
  //   console.warn('config.buildDir is undefined, using default');
  //   config.buildDir = '/workspace';
  // }
  // console.log(`Using build directory: ${config.buildDir}`);



  // Proceed with bundling
  const w = configer(webConfigs, testName, projectConfig);

  // Build the web bundle
  const buildResult = await esbuild.build(w);

  if (buildResult.metafile) {
    await processMetafile(projectConfig, buildResult.metafile, 'web', testName);

    // Create HTML files for each output
    const outputFiles = Object.keys(buildResult.metafile.outputs);
    for (const outputFile of outputFiles) {

      if (true) {
        const htmlPath = `testeranto/bundles/webtests/src/ts/Calculator.test.ts.html`;

        // Ensure the directory exists
        await fs.promises.mkdir(path.dirname(htmlPath), { recursive: true });

        // Create HTML content
        const htmlContent = `<!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Test Runner</title>
        <script type="module" src="Calculator.test.mjs"></script>
    </head>
    <body>
        <div id="root"></div>
        
    </body>
    </html>`;

        await fs.promises.writeFile(htmlPath, htmlContent);
        console.log(`Created HTML file: ${htmlPath}`);
      }
    }
  } else {
    console.warn("No metafile generated by esbuild");
  }

  console.log("WEB BUILDER: Metafiles have been generated");

  // TODO FIXME
  // In dev mode, keep the process alive
  if ("dev" === "dev") {
    console.log(
      "WEB BUILDER: Running in dev mode, keeping builder alive..."
    );

    // Watch for changes to rebuild metafiles
    const ctx = await esbuild.context(w);
    let { hosts, port } = await ctx.serve({
      host: 'webtests',
      // servedir: `testeranto/bundles/${testName}`,
      servedir: '.',
      onRequest: ({ method, path, remoteAddress, status, timeInMS }) => {
        console.log(`[esbuild] ${remoteAddress} - ${method} ${path} -> ${status} [${timeInMS}ms]`);
      },
    })
    console.log(
      `[WEB BUILDER]: esbuild server ${hosts}, ${port}`
    );

    // Keep the process alive
    process.on("SIGINT", async () => {
      console.log("WEB BUILDER: Shutting down...");
      process.exit(0);
    });


    try {
      const browser = await puppeteer.launch({
        args: [
          '--disable-dev-shm-usage',
          '--disable-gpu',
          '--disable-setuid-sandbox',
          '--no-sandbox',
          '--remote-allow-origins=*', // MANDATORY for cross-container access
          '--remote-debugging-address=0.0.0.0',
          '--remote-debugging-port=9222',
        ],
        // Automatically uses ENV PUPPETEER_EXECUTABLE_PATH
        executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || '/usr/bin/chromium-browser',
        headless: true,
        pipe: false
        // timeout: 60000 // Increase timeout to 60 seconds
      });

      console.log("Puppeteer launched successfully", browser);
    } catch (error) {
      console.error("Failed to launch Puppeteer:", error);
      process.exit(1);
    }

  }
}

async function main() {
  try {
    const nodeConfigs = (await import(nodeConfigPath)).default;
    const projectConfigs = (await import(projectConfigPath)).default;
    await startBundling(nodeConfigs, projectConfigs);
  } catch (error) {
    console.error("NODE BUILDER: Error importing config:", nodeConfigPath, error);
    console.error(error);
    process.exit(1);
  }
}

main();
