
import esbuild from "esbuild";
import puppeteer from "puppeteer-core";
import configer from "./esbuild";
import { processMetafile } from "../common";
import * as fs from "fs";
import * as path from "path";
import type { ITestconfigV2 } from "../../../Types";

console.log(process.cwd())
const urlDomain = `http://webtests:8000/`;

const projectConfigPath = process.argv[2];
const nodeConfigPath = process.argv[3];
const testName = process.argv[4];

async function startBundling(
  webConfigs: any,
  projectConfig: ITestconfigV2
) {
  console.log(`[WEB BUILDER] is now bundling: ${testName}`);

  const w = configer(webConfigs, testName, projectConfig);

  // Check if we're in dev mode
  const isDevMode = process.env.MODE === 'dev' || process.argv.includes('dev');
  
  if (isDevMode) {
    console.log(`[WEB BUILDER] Running in dev mode - starting watch mode`);
    
    // Create a build context for watch mode
    const ctx = await esbuild.context(w);
    
    // Build once initially
    const buildResult = await ctx.rebuild();
    if (buildResult.metafile) {
      await processMetafile(projectConfig, buildResult.metafile, 'web', testName);
      
      // Create HTML files for each output
      const outputFiles = Object.keys(buildResult.metafile.outputs);
      for (const outputFile of outputFiles) {
        const htmlPath = `testeranto/bundles/webtests/src/ts/Calculator.test.ts.html`;
        await fs.promises.mkdir(path.dirname(htmlPath), { recursive: true });
        const htmlContent = `<!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Test Runner</title>
        <script type="module" src="Calculator.test.mjs"></script>
    </head>
    <body>
        <div id="root"></div>
    </body>
    </html>`;
        await fs.promises.writeFile(htmlPath, htmlContent);
        console.log(`Created HTML file: ${htmlPath}`);
      }
    } else {
      console.warn("No metafile generated by esbuild");
    }
    
    // Start a dev server
    let { hosts, port } = await ctx.serve({
      host: 'webtests',
      servedir: '.',
      onRequest: ({ method, path, remoteAddress, status, timeInMS }) => {
        console.log(`[esbuild] ${remoteAddress} - ${method} ${path} -> ${status} [${timeInMS}ms]`);
      },
    });
    console.log(`[WEB BUILDER]: esbuild server ${hosts}, ${port}`);
    
    // Start watching for changes
    await ctx.watch();
    
    console.log(`[WEB BUILDER] Watch mode active - waiting for file changes...`);
    
    // Handle rebuild events
    ctx.on('rebuild', async (result) => {
      console.log(`[WEB BUILDER] Rebuilding due to file changes...`);
      if (result.metafile) {
        await processMetafile(projectConfig, result.metafile, 'web', testName);
        console.log(`[WEB BUILDER] Metafile updated`);
        
        // Trigger test re-run by touching inputFiles.json
        const outputBaseName = w.entryPoints?.[0]?.split('.').slice(0, -1).join('.') || testName;
        const inputFilesPath = `testeranto/bundles/${testName}/${outputBaseName}.mjs-inputFiles.json`;
        try {
          const stats = fs.statSync(inputFilesPath);
          fs.utimesSync(inputFilesPath, stats.atime, new Date());
          console.log(`[WEB BUILDER] Triggered inputFiles.json update`);
        } catch (error) {
          console.error(`[WEB BUILDER] Failed to trigger inputFiles.json update:`, error);
        }
      }
    });
    
    // Keep the process alive
    process.on("SIGINT", async () => {
      console.log("WEB BUILDER: Shutting down...");
      await ctx.dispose();
      process.exit(0);
    });
    
    console.log("Chrome is a separate service, not launched in builder");
    
  } else {
    // Once mode - just build once
    const buildResult = await esbuild.build(w);
    if (buildResult.metafile) {
      await processMetafile(projectConfig, buildResult.metafile, 'web', testName);
      
      // Create HTML files for each output
      const outputFiles = Object.keys(buildResult.metafile.outputs);
      for (const outputFile of outputFiles) {
        const htmlPath = `testeranto/bundles/webtests/src/ts/Calculator.test.ts.html`;
        await fs.promises.mkdir(path.dirname(htmlPath), { recursive: true });
        const htmlContent = `<!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Test Runner</title>
        <script type="module" src="Calculator.test.mjs"></script>
    </head>
    <body>
        <div id="root"></div>
    </body>
    </html>`;
        await fs.promises.writeFile(htmlPath, htmlContent);
        console.log(`Created HTML file: ${htmlPath}`);
      }
    } else {
      console.warn("No metafile generated by esbuild");
    }
    console.log("WEB BUILDER: Metafiles have been generated");
  }
}

async function main() {
  try {
    const nodeConfigs = (await import(nodeConfigPath)).default;
    const projectConfigs = (await import(projectConfigPath)).default;
    await startBundling(nodeConfigs, projectConfigs);
  } catch (error) {
    console.error("NODE BUILDER: Error importing config:", nodeConfigPath, error);
    console.error(error);
    process.exit(1);
  }
}

main();
