import * as path from 'path';
import * as fs from 'fs';

export const GenericConverter = {
  name: 'generic',
  
  detect(filePath: string): boolean {
    // Generic converter is the fallback - always return true if file exists
    // Other converters will have returned false if they matched
    return fs.existsSync(filePath);
  },
  
  generateWrapper(
    entryPointPath: string, 
    detectionResult: any, 
    translationResult: any, 
    filesHash: string
  ): string {
    const originalTestAbs = path.resolve(entryPointPath);
    const framework = detectionResult.frameworkType || 'unknown';
    
    return `// Generic test wrapper generated by testeranto
// Hash: ${filesHash}
// Framework: ${framework}
// This file loads the test file

import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Generic execution for unknown frameworks
try {
  await import('${originalTestAbs}');
  console.log('Test imported successfully');
} catch (error) {
  console.error('Failed to run test:', error);
  process.exit(1);
}
`;
  },
  
  translateToTesteranto(detectionResult: any): any {
    const framework = detectionResult.frameworkType || 'unknown';
    
    return {
      specification: `// Generated specification for ${framework} tests
const specification = (Suite, Given, When, Then) => [
  Suite("${framework} Tests", {
    "test": Given(
      ["${framework} test suite"],
      [
        When("run test", (store) => {
          // Test execution
          return store;
        })
      ],
      [
        Then("verify assertions", async (store) => {
          // Assertions
          return store;
        })
      ]
    )
  })
];`,
      
      implementation: `// Generated implementation for ${framework} tests
const implementation = {
  suites: {
    Default: "${framework} test suite"
  },
  givens: {
    Default: () => ({ /* Test context */ })
  },
  whens: {
    runTest: (testName) => (store) => {
      console.log('Running test:', testName);
      return store;
    }
  },
  thens: {
    verify: (expected) => (store) => {
      // Verify assertions
      return store;
    }
  }
};`,
      
      adapter: `// Generated adapter for ${framework} tests
const adapter = {
  beforeAll: async (input, testResource) => {
    console.log('${framework} beforeAll');
    return input;
  },
  beforeEach: async (subject, initializer, testResource, initialValues) => {
    console.log('${framework} beforeEach');
    return subject;
  },
  execute: async (store, actionCB, testResource) => {
    return actionCB(store);
  },
  verify: async (store, checkCB, testResource) => {
    return checkCB(store);
  },
  cleanupEach: async (store, key) => {
    console.log('${framework} cleanupEach');
    return store;
  },
  cleanupAll: async (store) => {
    console.log('${framework} cleanupAll');
    return store;
  },
  assert: (x) => !!x
};`
    };
  }
};
