import * as path from 'path';
import * as fs from 'fs';
import * as parser from '@babel/parser';
import traverse from '@babel/traverse';

export const JasmineConverter = {
  name: 'jasmine',
  
  detect(filePath: string): boolean {
    if (!fs.existsSync(filePath)) return false;
    
    const content = fs.readFileSync(filePath, 'utf-8');
    
    try {
      const ast = parser.parse(content, {
        sourceType: 'module',
        plugins: ['typescript', 'jsx']
      });
      
      let hasJasmineImport = false;
      
      traverse(ast, {
        ImportDeclaration(path) {
          const source = path.node.source.value;
          if (typeof source === 'string') {
            if (source === 'jasmine' || source.includes('@types/jasmine')) {
              hasJasmineImport = true;
            }
          }
        }
      });
      
      return hasJasmineImport;
      
    } catch (error) {
      return false;
    }
  },
  
  generateWrapper(
    entryPointPath: string, 
    detectionResult: any, 
    translationResult: any, 
    filesHash: string
  ): string {
    const originalTestAbs = path.resolve(entryPointPath);
    
    return `// Jasmine test wrapper generated by testeranto
// Hash: ${filesHash}
// Framework: jasmine
// This file loads and executes Jasmine tests

import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

console.log('Running Jasmine test: ${originalTestAbs}');

// Jasmine uses describe/it syntax similar to Mocha
const testModule = await import('${originalTestAbs}');

// Check for Jasmine environment
if (typeof jasmine !== 'undefined') {
  console.log('Jasmine environment detected');
} else if (typeof describe === 'function' && typeof it === 'function') {
  console.log('describe/it environment available (may be Mocha or Jasmine)');
} else {
  console.warn('Jasmine environment not detected. Tests may need manual execution.');
}

console.log('Jasmine test import completed');
`;
  },
  
  translateToTesteranto(detectionResult: any): any {
    return {
      specification: `// Generated specification for Jasmine tests
const specification = (Suite, Given, When, Then) => [
  Suite("Jasmine Tests", {
    "jasmine-test": Given(
      ["Jasmine test suite"],
      [
        When("run jasmine test", (store) => {
          // Jasmine test execution
          return store;
        })
      ],
      [
        Then("verify jasmine assertions", async (store) => {
          // Jasmine assertions
          return store;
        })
      ]
    )
  })
];`,
      
      implementation: `// Generated implementation for Jasmine tests
const implementation = {
  suites: {
    Default: "Jasmine test suite"
  },
  givens: {
    Default: () => ({ /* Jasmine test context */ })
  },
  whens: {
    runTest: (testName) => (store) => {
      console.log('Running Jasmine test:', testName);
      return store;
    }
  },
  thens: {
    verify: (expected) => (store) => {
      // Verify Jasmine assertions
      return store;
    }
  }
};`,
      
      adapter: `// Generated adapter for Jasmine tests
const adapter = {
  beforeAll: async (input, testResource) => {
    // Jasmine beforeAll
    console.log('Jasmine beforeAll');
    return input;
  },
  beforeEach: async (subject, initializer, testResource, initialValues) => {
    // Jasmine beforeEach
    console.log('Jasmine beforeEach');
    return subject;
  },
  execute: async (store, actionCB, testResource) => {
    // Execute Jasmine test action
    return actionCB(store);
  },
  verify: async (store, checkCB, testResource) => {
    // Verify Jasmine assertions
    return checkCB(store);
  },
  cleanupEach: async (store, key) => {
    // Jasmine afterEach
    console.log('Jasmine cleanupEach');
    return store;
  },
  cleanupAll: async (store) => {
    // Jasmine afterAll
    console.log('Jasmine cleanupAll');
    return store;
  },
  assert: (x) => !!x
};`
    };
  }
};
