import * as path from 'path';
import * as fs from 'fs';
import * as parser from '@babel/parser';
import traverse from '@babel/traverse';
import * as t from '@babel/types';

export const JestConverter = {
  name: 'jest',
  
  detect(filePath: string): boolean {
    if (!fs.existsSync(filePath)) return false;
    
    const content = fs.readFileSync(filePath, 'utf-8');
    
    try {
      const ast = parser.parse(content, {
        sourceType: 'module',
        plugins: ['typescript', 'jsx']
      });
      
      let hasJestImport = false;
      
      traverse(ast, {
        ImportDeclaration(path) {
          const source = path.node.source.value;
          if (typeof source === 'string') {
            if (source === 'jest' || source.startsWith('@jest/')) {
              hasJestImport = true;
            }
          }
        }
      });
      
      return hasJestImport;
      
    } catch (error) {
      // If AST parsing fails, don't detect as Jest
      return false;
    }
  },
  
  generateWrapper(
    entryPointPath: string, 
    detectionResult: any, 
    translationResult: any, 
    filesHash: string
  ): string {
    const originalTestAbs = path.resolve(entryPointPath);
    
    return `// Jest test wrapper generated by testeranto
// Hash: ${filesHash}
// Framework: jest
// This file loads and executes Jest tests

import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Import Jest and configure it
import { jest } from '@jest/globals';

// We need to run Jest programmatically
// For now, we'll import the original test file which should trigger Jest
// when the test runner is Jest

console.log('Running Jest test: ${originalTestAbs}');

// Import the test file - Jest will pick it up if we're in a Jest environment
// If not, we need to manually run the tests
const testModule = await import('${originalTestAbs}');

// If we're not in Jest environment, we need to provide a basic runner
if (typeof jest === 'undefined') {
  console.warn('Jest not found in global scope. Tests may not run properly.');
  
  // Try to detect test functions and run them manually
  const testExports = Object.keys(testModule);
  console.log('Test exports found:', testExports);
  
  // For simple cases, we can try to execute describe/it blocks
  // This is a fallback mechanism
  if (typeof describe === 'function') {
    // Mocha-like environment is available
    console.log('Using describe/it environment for Jest tests');
  }
}

console.log('Jest test import completed');
`;
  },
  
  translateToTesteranto(detectionResult: any): any {
    const structure = detectionResult.testStructure || {};
    
    return {
      specification: `// Generated specification for Jest tests
const specification = (Suite, Given, When, Then) => [
  ${structure.testSuites?.map((suite: any) => 
    `Suite("${suite.name || 'Jest Suite'}", {
      "${suite.name || 'test'}": Given(
        ["Jest test suite: ${suite.name || 'unnamed'}"],
        [
          ${structure.testCases?.map((testCase: any) => 
            `When("${testCase.name || 'unnamed test'}", (store) => {
              // Jest test: ${testCase.name}
              return store;
            })`
          ).join(',\n          ') || 'When("placeholder", (store) => store)'}
        ],
        [
          Then("Jest assertions pass", async (store) => {
            // Jest assertions would be verified here
            return store;
          })
        ]
      )
    })`
  ).join(',\n  ') || 'Suite("Jest Tests", {})'}
];`,
      
      implementation: `// Generated implementation for Jest tests
const implementation = {
  suites: {
    Default: "Jest test suite"
  },
  givens: {
    Default: () => ({ /* Jest test context */ })
  },
  whens: {
    runTest: (testName) => (store) => {
      console.log('Running Jest test:', testName);
      return store;
    }
  },
  thens: {
    verify: (expected) => (store) => {
      // Verify Jest assertions
      return store;
    }
  }
};`,
      
      adapter: `// Generated adapter for Jest tests
const adapter = {
  beforeAll: async (input, testResource) => {
    // Jest global setup
    console.log('Jest beforeAll');
    return input;
  },
  beforeEach: async (subject, initializer, testResource, initialValues) => {
    // Jest beforeEach hook
    console.log('Jest beforeEach');
    return subject;
  },
  execute: async (store, actionCB, testResource) => {
    // Execute Jest test action
    return actionCB(store);
  },
  verify: async (store, checkCB, testResource) => {
    // Verify Jest assertions
    return checkCB(store);
  },
  cleanupEach: async (store, key) => {
    // Jest afterEach hook
    console.log('Jest cleanupEach');
    return store;
  },
  cleanupAll: async (store) => {
    // Jest afterAll hook
    console.log('Jest cleanupAll');
    return store;
  },
  assert: (x) => !!x
};`
    };
  }
};
