import * as path from 'path';
import * as fs from 'fs';

export const MochaConverter = {
  name: 'mocha',
  
  detect(filePath: string): boolean {
    if (!fs.existsSync(filePath)) return false;
    
    const content = fs.readFileSync(filePath, 'utf-8');
    
    // Check for Mocha imports
    const hasMochaImport = content.includes('mocha') || 
                          content.includes('@types/mocha');
    
    // Check for Mocha patterns without Jest
    const hasMochaPatterns = content.includes('describe(') && 
                            content.includes('it(') &&
                            !content.includes('jest');
    
    return hasMochaImport || hasMochaPatterns;
  },
  
  generateWrapper(
    entryPointPath: string, 
    detectionResult: any, 
    translationResult: any, 
    filesHash: string
  ): string {
    const originalTestAbs = path.resolve(entryPointPath);
    
    return `// Mocha test wrapper generated by testeranto
// Hash: ${filesHash}
// Framework: mocha
// This file loads and executes Mocha tests

import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

console.log('Running Mocha test: ${originalTestAbs}');

// Mocha tests typically use describe/it syntax
// We'll import the test file which should register tests with Mocha
const testModule = await import('${originalTestAbs}');

// If Mocha is not running, we might need to manually execute
if (typeof describe === 'function' && typeof it === 'function') {
  console.log('Mocha describe/it functions available');
} else {
  console.warn('Mocha environment not detected. Tests may need manual execution.');
  
  // Try to find and run test functions
  const testExports = Object.keys(testModule);
  console.log('Available exports:', testExports);
}

console.log('Mocha test import completed');
`;
  },
  
  translateToTesteranto(detectionResult: any): any {
    return {
      specification: `// Generated specification for Mocha tests
const specification = (Suite, Given, When, Then) => [
  Suite("Mocha Tests", {
    "mocha-test": Given(
      ["Mocha test suite"],
      [
        When("run mocha test", (store) => {
          // Mocha test execution
          return store;
        })
      ],
      [
        Then("verify mocha assertions", async (store) => {
          // Mocha assertions
          return store;
        })
      ]
    )
  })
];`,
      
      implementation: `// Generated implementation for Mocha tests
const implementation = {
  suites: {
    Default: "Mocha test suite"
  },
  givens: {
    Default: () => ({ /* Mocha test context */ })
  },
  whens: {
    runTest: (testName) => (store) => {
      console.log('Running Mocha test:', testName);
      return store;
    }
  },
  thens: {
    verify: (expected) => (store) => {
      // Verify Mocha assertions
      return store;
    }
  }
};`,
      
      adapter: `// Generated adapter for Mocha tests
const adapter = {
  beforeAll: async (input, testResource) => {
    // Mocha before() hook
    console.log('Mocha beforeAll');
    return input;
  },
  beforeEach: async (subject, initializer, testResource, initialValues) => {
    // Mocha beforeEach() hook
    console.log('Mocha beforeEach');
    return subject;
  },
  execute: async (store, actionCB, testResource) => {
    // Execute Mocha test action
    return actionCB(store);
  },
  verify: async (store, checkCB, testResource) => {
    // Verify Mocha assertions
    return checkCB(store);
  },
  cleanupEach: async (store, key) => {
    // Mocha afterEach() hook
    console.log('Mocha cleanupEach');
    return store;
  },
  cleanupAll: async (store) => {
    // Mocha after() hook
    console.log('Mocha cleanupAll');
    return store;
  },
  assert: (x) => !!x
};`
    };
  }
};
