import * as path from 'path';
import * as fs from 'fs';
import * as parser from '@babel/parser';
import traverse from '@babel/traverse';

export const VitestConverter = {
  name: 'vitest',
  
  detect(filePath: string): boolean {
    if (!fs.existsSync(filePath)) return false;
    
    const content = fs.readFileSync(filePath, 'utf-8');
    
    try {
      const ast = parser.parse(content, {
        sourceType: 'module',
        plugins: ['typescript', 'jsx']
      });
      
      let hasVitestImport = false;
      
      traverse(ast, {
        ImportDeclaration(path) {
          const source = path.node.source.value;
          if (typeof source === 'string') {
            if (source === 'vitest' || source.startsWith('@vitest/')) {
              hasVitestImport = true;
            }
          }
        }
      });
      
      return hasVitestImport;
      
    } catch (error) {
      return false;
    }
  },
  
  generateWrapper(
    entryPointPath: string, 
    detectionResult: any, 
    translationResult: any, 
    filesHash: string
  ): string {
    const originalTestAbs = path.resolve(entryPointPath);
    
    return `// Vitest test wrapper generated by testeranto
// Hash: ${filesHash}
// Framework: vitest
// This file loads and executes Vitest tests

import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

console.log('Running Vitest test: ${originalTestAbs}');

// Vitest uses similar syntax to Jest but with different imports
// We'll import the test file which should register with Vitest
const testModule = await import('${originalTestAbs}');

// Check for Vitest environment
if (typeof import.meta !== 'undefined' && import.meta.vitest) {
  console.log('Vitest environment detected');
} else {
  console.warn('Vitest environment not detected. Tests may need manual execution.');
}

console.log('Vitest test import completed');
`;
  },
  
  translateToTesteranto(detectionResult: any): any {
    return {
      specification: `// Generated specification for Vitest tests
const specification = (Suite, Given, When, Then) => [
  Suite("Vitest Tests", {
    "vitest-test": Given(
      ["Vitest test suite"],
      [
        When("run vitest test", (store) => {
          // Vitest test execution
          return store;
        })
      ],
      [
        Then("verify vitest assertions", async (store) => {
          // Vitest assertions
          return store;
        })
      ]
    )
  })
];`,
      
      implementation: `// Generated implementation for Vitest tests
const implementation = {
  suites: {
    Default: "Vitest test suite"
  },
  givens: {
    Default: () => ({ /* Vitest test context */ })
  },
  whens: {
    runTest: (testName) => (store) => {
      console.log('Running Vitest test:', testName);
      return store;
    }
  },
  thens: {
    verify: (expected) => (store) => {
      // Verify Vitest assertions
      return store;
    }
  }
};`,
      
      adapter: `// Generated adapter for Vitest tests
const adapter = {
  beforeAll: async (input, testResource) => {
    // Vitest setup
    console.log('Vitest beforeAll');
    return input;
  },
  beforeEach: async (subject, initializer, testResource, initialValues) => {
    // Vitest beforeEach hook
    console.log('Vitest beforeEach');
    return subject;
  },
  execute: async (store, actionCB, testResource) => {
    // Execute Vitest test action
    return actionCB(store);
  },
  verify: async (store, checkCB, testResource) => {
    // Verify Vitest assertions
    return checkCB(store);
  },
  cleanupEach: async (store, key) => {
    // Vitest afterEach hook
    console.log('Vitest cleanupEach');
    return store;
  },
  cleanupAll: async (store) => {
    // Vitest teardown
    console.log('Vitest cleanupAll');
    return store;
  },
  assert: (x) => !!x
};`
    };
  }
};
